# Generated by Django 6.0.1 on 2026-02-06 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("student_created", "Student Created"),
                            ("student_updated", "Student Updated"),
                            ("parent_created", "Parent Created"),
                            ("parent_updated", "Parent Updated"),
                            ("staff_created", "Staff Created"),
                            ("staff_updated", "Staff Updated"),
                            ("result_published", "Result Published"),
                            ("result_updated", "Result Updated"),
                            ("fee_paid", "Fee Paid"),
                            ("fee_updated", "Fee Updated"),
                            ("announcement", "Announcement"),
                            ("system", "System Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("user_name", models.CharField(blank=True, max_length=255)),
                ("user_role", models.CharField(blank=True, max_length=50)),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User"),
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("staff", "Staff"),
                            ("result", "Result"),
                            ("fee", "Fee"),
                            ("announcement", "Announcement"),
                            ("system", "System"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=100, null=True)),
                ("target_name", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="users_activ_created_4767f2_idx"
                    ),
                    models.Index(
                        fields=["activity_type"], name="users_activ_activit_df2552_idx"
                    ),
                    models.Index(
                        fields=["user"], name="users_activ_user_id_4691b0_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="users_activ_is_read_4aa739_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="users_activ_target__53428e_idx",
                    ),
                ],
            },
        ),
    ]
