# Generated by Django 6.0.1 on 2026-01-21 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("parents", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of enrollment",
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique enrollment number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("withdrawn", "Withdrawn"),
                            ("transferred", "Transferred"),
                            ("graduated", "Graduated"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        help_text="Enrollment status",
                        max_length=20,
                    ),
                ),
                (
                    "is_repeating",
                    models.BooleanField(
                        default=False, help_text="Is student repeating this class?"
                    ),
                ),
                (
                    "is_promoted",
                    models.BooleanField(
                        default=False,
                        help_text="Has student been promoted from previous class?",
                    ),
                ),
                (
                    "promotion_date",
                    models.DateField(blank=True, help_text="Promotion date", null=True),
                ),
                (
                    "days_present",
                    models.IntegerField(
                        default=0, help_text="Days present in this enrollment"
                    ),
                ),
                (
                    "days_absent",
                    models.IntegerField(
                        default=0, help_text="Days absent in this enrollment"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Enrollment remarks"),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, help_text="Approval date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "ordering": ["-enrollment_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("art", "Arts/Humanities"),
                            ("general", "General (No stream yet)"),
                            ("technical", "Technical"),
                            ("none", "Not Applicable (Primary School)"),
                        ],
                        default="none",
                        help_text="Secondary school stream (Science/Commercial/Arts)",
                        max_length=20,
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date student was admitted",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        blank=True,
                        help_text="School admission number (e.g., CTS_2024_001)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        help_text="School-specific student ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "age_at_admission",
                    models.PositiveIntegerField(
                        blank=True, help_text="Student's age when admitted", null=True
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True,
                        help_text="Student's place of birth (City, State)",
                        max_length=200,
                    ),
                ),
                (
                    "home_language",
                    models.CharField(
                        blank=True,
                        help_text="Primary language spoken at home",
                        max_length=100,
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("red", "Red House"),
                            ("blue", "Blue House"),
                            ("green", "Green House"),
                            ("yellow", "Yellow House"),
                            ("purple", "Purple House"),
                            ("orange", "Orange House"),
                            ("none", "No House Assigned"),
                        ],
                        default="none",
                        help_text="House/Group assignment",
                        max_length=20,
                    ),
                ),
                (
                    "previous_class",
                    models.CharField(
                        blank=True, help_text="Previous class attended", max_length=50
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, help_text="Name of previous school", max_length=200
                    ),
                ),
                (
                    "transfer_certificate_no",
                    models.CharField(
                        blank=True,
                        help_text="Transfer certificate number",
                        max_length=50,
                    ),
                ),
                (
                    "is_prefect",
                    models.BooleanField(
                        default=False, help_text="Is this student a prefect?"
                    ),
                ),
                (
                    "prefect_role",
                    models.CharField(
                        blank=True, help_text="Prefect role/position", max_length=100
                    ),
                ),
                (
                    "student_category",
                    models.CharField(
                        choices=[
                            ("day", "Day Student"),
                            ("boarding", "Boarding Student"),
                            ("special_needs", "Special Needs Student"),
                            ("scholarship", "Scholarship Student"),
                            ("repeat", "Repeating Student"),
                            ("new", "New Student"),
                        ],
                        default="day",
                        help_text="Student category/type",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, help_text="Emergency contact phone", max_length=15
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to student", max_length=50
                    ),
                ),
                (
                    "fee_status",
                    models.CharField(
                        choices=[
                            ("paid_full", "Paid in Full"),
                            ("paid_partial", "Partially Paid"),
                            ("not_paid", "Not Paid"),
                            ("scholarship", "On Scholarship"),
                            ("exempted", "Fee Exempted"),
                        ],
                        default="not_paid",
                        help_text="Current fee payment status",
                        max_length=20,
                    ),
                ),
                (
                    "total_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total fee amount for the term",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount paid so far",
                        max_digits=10,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Remaining balance to pay",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_payment_evidence",
                    models.ImageField(
                        blank=True,
                        help_text="Upload payment receipt/evidence",
                        null=True,
                        upload_to="fee_evidence/",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, help_text="Date of last fee payment", null=True
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AS", "AS"),
                            ("SS", "SS"),
                            ("AC", "AC"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "has_allergies",
                    models.BooleanField(
                        default=False, help_text="Does child have any allergies?"
                    ),
                ),
                (
                    "allergy_details",
                    models.TextField(
                        blank=True, help_text="Please specify allergies if any"
                    ),
                ),
                (
                    "has_received_vaccinations",
                    models.BooleanField(
                        default=True,
                        help_text="Has child received required vaccinations?",
                    ),
                ),
                (
                    "family_doctor_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of family doctor/clinic",
                        max_length=200,
                    ),
                ),
                (
                    "family_doctor_phone",
                    models.CharField(
                        blank=True, help_text="Doctor's phone number", max_length=15
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any known medical conditions"
                    ),
                ),
                (
                    "has_learning_difficulties",
                    models.BooleanField(
                        default=False,
                        help_text="Does child have any identified learning difficulties?",
                    ),
                ),
                (
                    "learning_difficulties_details",
                    models.TextField(
                        blank=True,
                        help_text="Please elaborate on learning difficulties or developmental needs",
                    ),
                ),
                ("birth_certificate_uploaded", models.BooleanField(default=False)),
                (
                    "birth_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Upload birth certificate",
                        null=True,
                        upload_to="student_documents/birth_certificates/",
                    ),
                ),
                ("student_image_uploaded", models.BooleanField(default=False)),
                (
                    "student_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload student photograph",
                        null=True,
                        upload_to="student_documents/images/",
                    ),
                ),
                ("immunization_record_uploaded", models.BooleanField(default=False)),
                (
                    "immunization_record",
                    models.FileField(
                        blank=True,
                        help_text="Upload immunization record",
                        null=True,
                        upload_to="student_documents/immunization/",
                    ),
                ),
                ("previous_school_report_uploaded", models.BooleanField(default=False)),
                (
                    "previous_school_report",
                    models.FileField(
                        blank=True,
                        help_text="Upload previous school report",
                        null=True,
                        upload_to="student_documents/reports/",
                    ),
                ),
                ("parent_id_copy_uploaded", models.BooleanField(default=False)),
                (
                    "parent_id_copy",
                    models.FileField(
                        blank=True,
                        help_text="Upload parent/guardian ID copy",
                        null=True,
                        upload_to="student_documents/parent_ids/",
                    ),
                ),
                (
                    "transportation_mode",
                    models.CharField(
                        choices=[
                            ("school_bus", "School Bus"),
                            ("parent_drop", "Parent Drop-off"),
                            ("public_transport", "Public Transport"),
                            ("walk", "Walks to School"),
                            ("other", "Other"),
                        ],
                        default="parent_drop",
                        help_text="Mode of transportation to school",
                        max_length=20,
                    ),
                ),
                (
                    "bus_route",
                    models.CharField(
                        blank=True,
                        help_text="Bus route (if using school bus)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is student currently active/enrolled?"
                    ),
                ),
                (
                    "is_graduated",
                    models.BooleanField(
                        default=False, help_text="Has student graduated?"
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, help_text="Date of graduation", null=True
                    ),
                ),
                ("days_present", models.PositiveIntegerField(default=0)),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("days_late", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current class/grade level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academic.classlevel",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="father_of_students",
                        to="parents.parent",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mother_of_students",
                        to="parents.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["class_level__order", "user__first_name"],
            },
        ),
    ]
