# Generated by Django 6.0.1 on 2026-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emergency contact person",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emergency contact phone",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Relationship to student",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="home_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary language spoken at home",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_prefect",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is this student a prefect?"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="place_of_birth",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Student's place of birth (City, State)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="previous_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Previous class attended",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="previous_school",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of previous school",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="transfer_certificate_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Transfer certificate number",
                max_length=50,
            ),
        ),
    ]
