# Generated by Django 5.2.12 on 2026-03-30 18:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_certificate",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload birth certificate",
                max_length=255,
                null=True,
                verbose_name="birth_certificate",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fee_payment_evidence",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload payment receipt/evidence",
                max_length=255,
                null=True,
                verbose_name="fee_payment_evidence",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload student photograph",
                max_length=255,
                null=True,
                verbose_name="student_image",
            ),
        ),
    ]
