# Generated by Django 6.0.1 on 2026-01-21 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique staff identification number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date staff was employed",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("volunteer", "Volunteer"),
                            ("trainee", "Trainee/Intern"),
                            ("probation", "Probation"),
                        ],
                        default="full_time",
                        help_text="Type of employment",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("administration", "Administration"),
                            ("academic", "Academic"),
                            ("finance", "Finance/Bursary"),
                            ("library", "Library"),
                            ("laboratory", "Laboratory"),
                            ("ict", "ICT/Computer"),
                            ("security", "Security"),
                            ("maintenance", "Maintenance"),
                            ("transport", "Transport"),
                            ("health", "Health Clinic"),
                            ("counseling", "Guidance & Counseling"),
                            ("sports", "Sports & Games"),
                            ("kitchen", "Kitchen/Cafeteria"),
                            ("none", "Not Applicable"),
                        ],
                        default="none",
                        help_text="Department/Unit assignment",
                        max_length=50,
                    ),
                ),
                (
                    "position_title",
                    models.CharField(
                        blank=True, help_text="Job title/position", max_length=100
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True,
                        help_text="Highest educational qualification (e.g., B.Sc, M.Ed, PhD)",
                        max_length=100,
                    ),
                ),
                (
                    "qualification_institution",
                    models.CharField(
                        blank=True,
                        help_text="Institution where qualification was obtained",
                        max_length=200,
                    ),
                ),
                (
                    "year_of_graduation",
                    models.IntegerField(
                        blank=True, help_text="Year of graduation", null=True
                    ),
                ),
                (
                    "professional_certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications (TRCN, etc.)"
                    ),
                ),
                (
                    "trcn_number",
                    models.CharField(
                        blank=True,
                        help_text="Teachers Registration Council of Nigeria Number",
                        max_length=50,
                    ),
                ),
                (
                    "trcn_expiry_date",
                    models.DateField(
                        blank=True, help_text="TRCN license expiry date", null=True
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True, help_text="Areas of specialization/expertise"
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Basic monthly salary",
                        max_digits=10,
                    ),
                ),
                (
                    "salary_scale",
                    models.CharField(
                        blank=True, help_text="Salary scale/grade level", max_length=50
                    ),
                ),
                (
                    "salary_step",
                    models.IntegerField(
                        default=1, help_text="Step within salary scale"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name for salary payments",
                        max_length=100,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="Account name as registered with bank",
                        max_length=100,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=20
                    ),
                ),
                (
                    "annual_leave_days",
                    models.IntegerField(
                        default=21, help_text="Annual leave entitlement in days"
                    ),
                ),
                (
                    "sick_leave_days",
                    models.IntegerField(
                        default=10, help_text="Annual sick leave entitlement in days"
                    ),
                ),
                (
                    "leave_days_taken",
                    models.IntegerField(
                        default=0, help_text="Leave days already taken"
                    ),
                ),
                (
                    "leave_days_remaining",
                    models.IntegerField(default=21, help_text="Remaining leave days"),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(
                        blank=True, help_text="Next of kin full name", max_length=100
                    ),
                ),
                (
                    "next_of_kin_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to staff", max_length=50
                    ),
                ),
                (
                    "next_of_kin_phone",
                    models.CharField(
                        blank=True, help_text="Next of kin phone number", max_length=15
                    ),
                ),
                (
                    "next_of_kin_address",
                    models.TextField(blank=True, help_text="Next of kin address"),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AS", "AS"),
                            ("SS", "SS"),
                            ("AC", "AC"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any known medical conditions"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=15,
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to staff", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is staff currently active/employed?"
                    ),
                ),
                (
                    "is_on_probation",
                    models.BooleanField(
                        default=False, help_text="Is staff on probation?"
                    ),
                ),
                (
                    "probation_end_date",
                    models.DateField(
                        blank=True, help_text="Probation end date", null=True
                    ),
                ),
                (
                    "is_retired",
                    models.BooleanField(default=False, help_text="Has staff retired?"),
                ),
                (
                    "retirement_date",
                    models.DateField(
                        blank=True, help_text="Date of retirement", null=True
                    ),
                ),
                (
                    "is_on_leave",
                    models.BooleanField(
                        default=False, help_text="Is staff currently on leave?"
                    ),
                ),
                (
                    "leave_start_date",
                    models.DateField(
                        blank=True, help_text="Leave start date", null=True
                    ),
                ),
                (
                    "leave_end_date",
                    models.DateField(blank=True, help_text="Leave end date", null=True),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Overall performance rating (0-5)",
                        max_digits=3,
                    ),
                ),
                (
                    "last_appraisal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last performance appraisal",
                        null=True,
                    ),
                ),
                (
                    "next_appraisal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of next performance appraisal",
                        null=True,
                    ),
                ),
                (
                    "appraisal_notes",
                    models.TextField(
                        blank=True, help_text="Performance appraisal notes"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload resume/CV",
                        null=True,
                        upload_to="staff_documents/resumes/",
                    ),
                ),
                (
                    "certificates",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificates",
                        null=True,
                        upload_to="staff_documents/certificates/",
                    ),
                ),
                (
                    "id_copy",
                    models.FileField(
                        blank=True,
                        help_text="Upload ID card copy",
                        null=True,
                        upload_to="staff_documents/ids/",
                    ),
                ),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Passport photograph",
                        null=True,
                        upload_to="staff_documents/photos/",
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0, help_text="Total years of work experience"
                    ),
                ),
                (
                    "previous_employers",
                    models.TextField(blank=True, help_text="Previous employers"),
                ),
                (
                    "references",
                    models.TextField(blank=True, help_text="Professional references"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "ordering": ["user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_all_students", models.BooleanField(default=False)),
                ("can_edit_student_records", models.BooleanField(default=False)),
                ("can_view_all_results", models.BooleanField(default=False)),
                ("can_edit_results", models.BooleanField(default=False)),
                ("can_publish_results", models.BooleanField(default=False)),
                ("can_view_all_staff", models.BooleanField(default=False)),
                ("can_edit_staff_records", models.BooleanField(default=False)),
                ("can_manage_staff_permissions", models.BooleanField(default=False)),
                ("can_view_financial_records", models.BooleanField(default=False)),
                ("can_manage_fees", models.BooleanField(default=False)),
                ("can_process_payments", models.BooleanField(default=False)),
                ("can_manage_classes", models.BooleanField(default=False)),
                ("can_manage_subjects", models.BooleanField(default=False)),
                ("can_manage_sessions", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Permission",
                "verbose_name_plural": "Staff Permissions",
            },
        ),
    ]
