# Generated by Django 6.0.1 on 2026-01-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="staff",
            field=models.OneToOneField(
                help_text="Staff member",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="staff.staff",
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["staff_id"], name="staff_staff_staff_i_1228db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["employment_type"], name="staff_staff_employm_56a539_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["department"], name="staff_staff_departm_eea1cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_active"], name="staff_staff_is_acti_0db61a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["trcn_number"], name="staff_staff_trcn_nu_2aabf8_idx"
            ),
        ),
    ]
