# Generated by Django 5.2.12 on 2026-03-30 21:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="certificates",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload certificates",
                max_length=255,
                null=True,
                verbose_name="certificates",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="id_copy",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload ID card copy",
                max_length=255,
                null=True,
                verbose_name="id_copy",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="passport_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Passport photograph",
                max_length=255,
                null=True,
                verbose_name="passport_photo",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="resume",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload resume/CV",
                max_length=255,
                null=True,
                verbose_name="resume",
            ),
        ),
    ]
