# Generated by Django 6.0.1 on 2026-01-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("relative", "Relative"),
                            ("other", "Other"),
                        ],
                        default="father",
                        help_text="Type of parent relationship",
                        max_length=20,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, help_text="Parent's occupation", max_length=100
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, help_text="Name of employer", max_length=200
                    ),
                ),
                (
                    "employer_address",
                    models.TextField(blank=True, help_text="Employer's address"),
                ),
                (
                    "office_phone",
                    models.CharField(
                        blank=True, help_text="Office phone number", max_length=15
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("married", "Married"),
                            ("single", "Single"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                        ],
                        default="married",
                        help_text="Marital status",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, help_text="Emergency contact phone", max_length=15
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to family", max_length=50
                    ),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("phone", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("in_person", "In Person"),
                        ],
                        default="whatsapp",
                        help_text="Preferred communication method",
                        max_length=20,
                    ),
                ),
                (
                    "receive_sms_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive SMS alerts about child"
                    ),
                ),
                (
                    "receive_email_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive email alerts about child"
                    ),
                ),
                (
                    "annual_income_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below_500k", "Below ₦500,000"),
                            ("500k_1m", "₦500,000 - ₦1 Million"),
                            ("1m_3m", "₦1 Million - ₦3 Million"),
                            ("3m_5m", "₦3 Million - ₦5 Million"),
                            ("above_5m", "Above ₦5 Million"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        help_text="Annual income range (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "parent_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique parent ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=100),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, help_text="Account name", max_length=100
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=20
                    ),
                ),
                (
                    "is_pta_member",
                    models.BooleanField(
                        default=False, help_text="Is parent a PTA member?"
                    ),
                ),
                (
                    "pta_position",
                    models.CharField(
                        blank=True, help_text="PTA position/role", max_length=100
                    ),
                ),
                (
                    "pta_committee",
                    models.CharField(
                        blank=True, help_text="PTA committee membership", max_length=100
                    ),
                ),
                (
                    "declaration_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Parent has accepted the declaration of truth",
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when declaration was accepted",
                        null=True,
                    ),
                ),
                (
                    "declaration_signature",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature (parent name)",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is parent active?"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Has parent been verified by school?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Spouse/Other parent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spouse_of",
                        to="parents.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "ordering": ["user__first_name"],
            },
        ),
    ]
