# Generated by Django 6.0.1 on 2026-01-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["parent_id"], name="parents_par_parent__2f28b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["parent_type"], name="parents_par_parent__65b94b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["is_pta_member"], name="parents_par_is_pta__d9168e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["is_verified"], name="parents_par_is_veri_a1e671_idx"
            ),
        ),
    ]
