# Generated by Django 6.0.1 on 2026-01-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., JSS 1 Three, SSS 2 Science A", max_length=100
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts/Humanities"),
                            ("general", "General"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("max_capacity", models.IntegerField(default=40)),
                ("current_enrollment", models.IntegerField(default=0)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("building", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["class_level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("creche", "Creche"),
                            ("nursery_1", "Nursery 1"),
                            ("nursery_2", "Nursery 2"),
                            ("kg_1", "Kindergarten 1 (KG 1)"),
                            ("kg_2", "Kindergarten 2 (KG 2)"),
                            ("primary_1", "Primary 1 (Basic 1)"),
                            ("primary_2", "Primary 2 (Basic 2)"),
                            ("primary_3", "Primary 3 (Basic 3)"),
                            ("primary_4", "Primary 4 (Basic 4)"),
                            ("primary_5", "Primary 5 (Basic 5)"),
                            ("primary_6", "Primary 6 (Basic 6)"),
                            ("jss_1", "JSS 1"),
                            ("jss_2", "JSS 2"),
                            ("jss_3", "JSS 3"),
                            ("sss_1", "SSS 1"),
                            ("sss_2", "SSS 2"),
                            ("sss_3", "SSS 3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("order", models.IntegerField(default=0)),
                ("min_age", models.IntegerField(default=0)),
                ("max_age", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("has_common_entrance", models.BooleanField(default=False)),
                ("has_bece", models.BooleanField(default=False)),
                ("has_waec_neco", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["program__program_type", "order"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_compulsory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("creche", "Creche"),
                            ("nursery", "Nursery"),
                            ("primary", "Primary School"),
                            ("junior_secondary", "Junior Secondary School (JSS)"),
                            ("senior_secondary", "Senior Secondary School (SSS)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("duration_years", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["program_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Subject"),
                            ("elective", "Elective Subject"),
                            ("vocational", "Vocational Subject"),
                            ("religious", "Religious Studies"),
                            ("language", "Language"),
                            ("science", "Science"),
                            ("arts", "Arts/Humanities"),
                            ("commercial", "Commercial/Business"),
                            ("technical", "Technical"),
                            ("pre_school", "Pre-School Subject"),
                        ],
                        default="core",
                        max_length=30,
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("science", "Science Stream"),
                            ("commercial", "Commercial Stream"),
                            ("arts", "Arts/Humanities Stream"),
                            ("general", "General (All Streams)"),
                            ("technical", "Technical Stream"),
                            ("pre_school", "Pre-School"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_compulsory", models.BooleanField(default=False)),
                ("is_examinable", models.BooleanField(default=True)),
                ("has_practical", models.BooleanField(default=False)),
                (
                    "ca_weight",
                    models.IntegerField(default=40, help_text="CA percentage (40%)"),
                ),
                (
                    "exam_weight",
                    models.IntegerField(default=60, help_text="Exam percentage (60%)"),
                ),
                (
                    "total_marks",
                    models.IntegerField(
                        default=100, help_text="Total marks obtainable"
                    ),
                ),
                (
                    "pass_mark",
                    models.IntegerField(default=40, help_text="Pass mark (40)"),
                ),
                ("available_for_creche", models.BooleanField(default=False)),
                ("available_for_nursery", models.BooleanField(default=False)),
                ("available_for_primary", models.BooleanField(default=False)),
                ("available_for_jss", models.BooleanField(default=False)),
                ("available_for_sss", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("class_teacher", "Class Teacher"),
                            ("subject_teacher", "Subject Teacher"),
                            ("head_of_department", "Head of Department"),
                            ("senior_teacher", "Senior Teacher"),
                            ("assistant_teacher", "Assistant Teacher"),
                        ],
                        default="subject_teacher",
                        max_length=30,
                    ),
                ),
                (
                    "stream_specialization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("science", "Science"),
                            ("commercial", "Commercial"),
                            ("arts", "Arts/Humanities"),
                            ("general", "General"),
                            ("technical", "Technical"),
                        ],
                        help_text="Stream specialization",
                        max_length=20,
                    ),
                ),
                (
                    "max_periods_per_week",
                    models.IntegerField(
                        default=30, help_text="Maximum teaching periods per week"
                    ),
                ),
                (
                    "current_periods_per_week",
                    models.IntegerField(
                        default=0, help_text="Current teaching periods per week"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
            },
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("first", "First Term"),
                            ("second", "Second Term"),
                            ("third", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("resumption_date", models.DateField(blank=True, null=True)),
                ("vacation_date", models.DateField(blank=True, null=True)),
                ("total_school_days", models.IntegerField(default=0)),
                ("total_teaching_weeks", models.IntegerField(default=0)),
                ("mid_term_break_start", models.DateField(blank=True, null=True)),
                ("mid_term_break_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="academic.academicsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session__start_date", "term"],
            },
        ),
    ]
