# Generated by Django 6.0.1 on 2026-01-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classlevel",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_levels",
                to="academic.program",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="assigned_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classes currently assigned to this teacher",
                related_name="subject_teachers",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="assistant_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classes where teacher is assistant",
                related_name="assistant_teachers",
                to="academic.class",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="class_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Class levels this teacher can teach",
                related_name="teachers",
                to="academic.classlevel",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="hod_subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects where teacher is HOD",
                related_name="hod_teachers",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="staff",
            field=models.OneToOneField(
                help_text="Linked staff record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects this teacher can teach",
                related_name="teachers",
                to="academic.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicterm",
            unique_together={("session", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("session", "term", "class_level", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="classlevel",
            unique_together={("program", "level")},
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
    ]
